dist: trusty
language: node_js
username: makoto
node_js:
  - "12.13.0"
cache: npm
github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
jobs:
  include:
    - stage: Deploy
      name: "Deploy"
      install:
        - npm i
      script: npm run deploy
notifications:
  email:
    - false
